spring.profiles.active=development

# This controls how long a JMS receive() waits before returning
# It's in milliseconds, so this is 5 seconds
spring.jms.template.receive-timeout=5000

ibm.mq.queueManager=QM1
ibm.mq.channel=DEV.ADMIN.SVRCONN
ibm.mq.connName=localhost(1414)
ibm.mq.user=admin
ibm.mq.password=passw0rd

# This is the queue the application is going to use
demo.mq.queue=DEV.QUEUE.1

# Which port will Tomcat listen on
server.port=${SERVER_PORT:8088}
