[flake8]
max-line-length=160
exclude=*CMQ*

# A minimal set of flake8 diagnostics that we choose to ignore
#
# E302 expected 2 blank lines
# W503 line break before binary operator
# W504 line break after binary operator
# F403 ‘from module import *’ used; unable to detect undefined names
# F405 <function> may be undefined, or defined from star imports
ignore=E302,
       W503, W504,
       F403, F405

# Some extra diagnostics that we choose to ignore on a per-file basis.
per-file-ignores=
      # Ignore the unused imports in _init__.py as they are there
      # to be available in other modules
      __init__.py: F401

# This section sets up the unittest environment
[testenv]
deps =
    -rcode/tests/requirements.txt
    pytest-cov

# "-x" means stop process after first failure
# I can't get the coverage stats to include all the files, maybe
# there's some magic. But I'm leaving the execution in here for now and
# will look again later.
# The default args passed from the runAllTests scripts are "-- code/tests". But
# we can use parameters to that script to drive specific tests.
commands =
    pytest -x {posargs}

